single:
  - GUID : a035e401-843c-4007-86d3-a97354e92296
    name : "about"
    alias:
      - 關於
    sleep: 20
    text : 我是小烈專屬機器人(灬ºωº灬)，你可以在GitHub上找到我（https://github.com/Codevience/Hyper2374Bot，開發者是傑森哥（@jason40418）Kappa
    level: general
  - GUID : 31cb0ae1-1e4d-4ff0-8244-b9f0cf92b002
    name : "facebook"
    alias:
      - fb
      - 臉書
    sleep: 20
    text : 小烈FB粉絲團： https://goo.gl/50ClFP 小烈娛樂團 TakeNRG
    level: general

  - GUID : d43f684b-5c08-49d0-9042-e079cf45d976
    name : "youtube"
    alias:
      - yt
      - 油管
    sleep: 20
    text : 小烈醬諧星日記： https://goo.gl/yz2WQK ，內含教學影片、小技巧、實況精華，請多多支持。
    level: general
random:
  - GUID : ffe05939-8ce0-4ae7-9aa4-9ef5414f9c6b
    name : "運勢"
    alias:
      - 籤運
    sleep: 20
    text :
      - 大吉
      - 中吉
      - 小吉
      - 吉
      - 末吉
      - 凶
      - 大凶
    level: general